force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>ORD-{0}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <formula>Account__r.Market__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>ORD_ITM-{0}</displayFormat>
        <label>Order Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/OrderItem_Redirect_Controller.cls
public with sharing class OrderItem_Redirect_Controller {
	Order_Item__c oi;
	Order__c order;
    String orderId;
    String marketName;
    
	public OrderItem_Redirect_Controller(ApexPages.StandardController controller) {
		this.oi = (Order_Item__c)controller.getRecord();
        if (this.oi.Id == null) {
            Map<String, String> pageParams = ApexPages.currentPage().getParameters();
            if (pageParams.containsKey('order')) {
                this.orderId = pageParams.get('order');
				this.order = [SELECT Id, Account__c, RecordTypeId, Account__r.Market__r.Name FROM Order__c WHERE Id =:this.orderId];
                this.marketName = this.order.Account__r.Market__r.Name;
            }
        } else {
			this.oi = [SELECT Order__c, Order__r.Account__c, Order__r.RecordTypeId, Order__r.Account__r.Market__r.Name FROM Order_Item__c WHERE Id =:oi.Id];            
            this.orderId = this.oi.Order__c;
            this.marketName = this.oi.Order__r.Account__r.Market__r.Name;
        }
        
	}
	
	public PageReference Redirect() {
        PageReference ref = Page.orderItemsHTML;            
        
		ref.getParameters().put('Id', this.orderId);
        ref.getParameters().put('retUrl',this.orderId);
		return ref;
	}
}